/**
 * The field-note index, as the apex domain sees it.
 *
 * `data/notes.json` is generated by `python3 tools/notes.py` on every ship —
 * the same arrangement as `data/species.json`, and for the same reason: the
 * publication is a separate Vercel project with its own Root Directory, so a
 * build here cannot read witness_web/community. The notes themselves stay
 * over there. This file carries only enough to link them.
 */
import notesJson from "@/data/notes.json";

export type NoteIndexEntry = {
  slug: string;
  title: string;
  date: string;
  description: string;
  section: string;
  /** Archive record ids the note links, so a record can link back. */
  records: string[];
};

export const NOTES = notesJson as NoteIndexEntry[];

/** Newest first, as the manifest is written. */
export function allNotes(): NoteIndexEntry[] {
  return NOTES;
}

export function notesForRecord(id: string): NoteIndexEntry[] {
  return NOTES.filter((note) => note.records.includes(id));
}

export function noteUrl(slug: string): string {
  return `https://community.witnessatlas.com/p/${slug}`;
}

const SECTION_NAMES: Record<string, string> = {
  species: "Species",
  numbers: "Numbers",
  half: "Half the Earth",
  policy: "Policy",
  dispatches: "Dispatches",
  attention: "Attention",
};

export function sectionName(key: string): string {
  return SECTION_NAMES[key] ?? "Field Notes";
}
