#!/usr/bin/env python3
"""Turn Natural Earth 110m land (public domain) into the SVG path behind /map.

Usage: python3 tools/build_world_land.py > witness_web/site/lib/world-land.ts

Plate Carrée at 3 units per degree; frame lon -180..180, lat 84..-56, so the
viewBox is 0 0 1080 420. Antarctica is dropped (every ring below -56). Every
other ring is emitted, holes included: the Caspian Sea is a hole in the
Eurasia polygon and the default nonzero fill rule renders it as water.
"""
import json
import sys
import urllib.request

URL = "https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_110m_land.geojson"
K, LAT_TOP, LAT_BOTTOM = 3, 84, -56
W, H = 360 * K, (LAT_TOP - LAT_BOTTOM) * K


def px(lon, lat):
    return round((lon + 180) * K, 1), round((LAT_TOP - lat) * K, 1)


assert px(0, 84) == (540, 0) and px(180, -56) == (1080, 420)

with urllib.request.urlopen(URL) as response:
    features = json.load(response)["features"]

rings, total = [], 0
for feature in features:
    geometry = feature["geometry"]
    polygons = [geometry["coordinates"]] if geometry["type"] == "Polygon" else geometry["coordinates"]
    for polygon in polygons:
        for ring in polygon:
            total += 1
            if max(point[1] for point in ring) < LAT_BOTTOM:
                continue  # Antarctica
            rings.append(ring)

parts = []
for ring in rings:
    points = [px(point[0], point[1]) for point in ring]
    if points[-1] == points[0]:
        points.pop()  # Z closes the ring; GeoJSON repeats the first point
    parts.append("M" + "L".join(f"{x:g},{y:g}" for x, y in points) + "Z")
d = "".join(parts)

assert 5_000 < len(d) < 120_000, len(d)
sys.stderr.write(f"{len(rings)} of {total} rings kept, {len(d)} chars\n")
print(f"""// GENERATED by tools/build_world_land.py. Do not edit by hand.
// Natural Earth 110m land, public domain (no attribution required), projected
// Plate Carrée at {K} units per degree into a {W} x {H} frame
// (lon -180..180, lat {LAT_TOP}..{LAT_BOTTOM}; Antarctica dropped).
export const LAND_D =
  "{d}";""")
